### ISSUE TITLE
no validation on discord ID

### ISSUE THREAD

**Issue by pythonpete32** [aracred/bot#16]
https://github.com/aracred/AraCred/runs/600313413?check_suite_focus=true#step:5:94

someone entered their discord ID incorrectly, as this is being uploaded directly to the `project.json` file, it is breaking the workflow and causing SC to fail. 
TODO: 
- [ ] add validation to discord id input

**Comment by crisog** [comment]
> https://github.com/aracred/AraCred/runs/600313413?check_suite_focus=true#step:5:94
> 
> someone entered their discord ID incorrectly, as this is being uploaded directly to the `project.json` file, it is breaking the workflow and causing SC to fail.
> TODO:
> 
> * [ ]  add validation to discord id input

I submitted a PR for something similar, but instead of validating the discord ID, it will be gathered automatically from the author of the message. If someone provides a discord ID, it will be overwritten with the correct one.

The PR is under review, I will fix reviewed things ASAP so it can be merged.
